application-builder: https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-application-clusterbuilder-0.5.0-snapshot-20191203141829-b3a6431b2238bee5.yaml
function-builder: https://storage.googleapis.com/projectriff/riff-buildtemplate/riff-function-clusterbuilder-0.5.0-snapshot-20191203141829-b3a6431b2238bee5.yaml
